// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWRrrCENip1aUcFrvmIKGM0wv_vmdAYiQ',
    appId: '1:536923896498:web:c0043a2298d9e96eea67ab',
    messagingSenderId: '536923896498',
    projectId: 'manish-notes',
    authDomain: 'manish-notes.firebaseapp.com',
    storageBucket: 'manish-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6gkWSbyFd6bmykknSo7z7CuXji_Q87J4',
    appId: '1:536923896498:android:edcb2307aced3a29ea67ab',
    messagingSenderId: '536923896498',
    projectId: 'manish-notes',
    storageBucket: 'manish-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjwxmdPUCuL8V8t3Ng4IHLCaKtH6pvoq0',
    appId: '1:536923896498:ios:acb74944ea783682ea67ab',
    messagingSenderId: '536923896498',
    projectId: 'manish-notes',
    storageBucket: 'manish-notes.appspot.com',
    iosBundleId: 'com.note.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjwxmdPUCuL8V8t3Ng4IHLCaKtH6pvoq0',
    appId: '1:536923896498:ios:a3c71c0b493c2854ea67ab',
    messagingSenderId: '536923896498',
    projectId: 'manish-notes',
    storageBucket: 'manish-notes.appspot.com',
    iosBundleId: 'com.note.myProject.RunnerTests',
  );
}
